### PR TITLE
Add PTL6015 slide pot

### PR DESCRIPTION
**Pull request by sebastianbeyer**

### CODE REVIEW

**Comment by holmesrichards** [comment]
I'd like to see a few changes:

* The symbol and footprint names are rather cryptic. Aside from well known semiconductors most of the symbol names I've used generally are both more descriptive and less specific, e.g. `R_SLIDE_POT` for _any_ 3-terminal slide pot. Footprints are specific to the part but include some description, e.g. `Potentiometer_Alpha_RA4520F_Single_Slide`. Maybe for instance use `R_SLIDE_POT_LED` and `Potentiometer_Bourns_PTL6015_Single_Slide_LED`.
* For consistency with the other pot symbols, the Reference should be RV.
* The symbol is a plain box which does not make clear the functionality. In particular it's not at all clear what the E1, B1, and L1 pins are for. (I had to look at the datasheet. B for anode and E for cathode and L for dummy? Not obvious!) How about making it a 2-unit symbol, with unit A a copy of `R_SLIDE_POT` and unit B a copy of `LED_*`? The dummy pin can be omitted entirely, I think, or it could be a hidden pin on the LED unit. Either way no point in having it visible on the symbol since it isn't used.

**Comment by sebastianbeyer** [comment]
Good points, I was a bit quick to submit this when I cleaned out a few of my files today ;)
I will make a revised version.

**Comment by sebastianbeyer** [comment]
I updated the branch and made all the suggested changes :) I should probably have made another commit, but I just amended the changes to the initial one. 
One other question: I named the pins for the LED A and K on the footprint and so I also had to give these characters as pin "numbers" in the symbol. I thought it would work by keeping the pin numbers and only using the pin names, but somehow not... It works as it is now, but I am not sure if it's best practice... What do you think?

**Comment by holmesrichards** [comment]
I can't claim to know what is best practice. But I think this seems fine.

**Pull request merged**
